site_name: Agentic-AI-PostgreSQL
site_description: Documentation and notes for the Agentic-AI-PostgreSQL project
repo_url: https://github.com/AgnosticDBA/Agentic-AI-PostgreSQL
theme:
  name: material
docs_dir: docs
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Architecture: architecture.md
  - Runbook: runbook.md
  - GitHub Credentials: github-credentials.md
  - Wiki & Notes: wiki-setup.md
